PHP = php
DOKU = doku.php

all:
	$(PHP) $(DOKU)

clean:
	rm htdocs/index.html
	rm -rf htdocs/blog
	rm -rf htdocs/v2ex-doc
	rm -rf htdocs/china-travel
	rm -rf htdocs/shanghai
	rm -rf htdocs/project-babel
	rm -rf htdocs/google-adsense
