#!/bin/bash
sudo apt-get install libming-dev
sudo apt-get install libmcrypt-dev
sudo apt-get install libfreetype6-dev
sudo apt-get install libtiff-dev
sudo apt-get install libpng12-dev
sudo apt-get install libjpeg-dev
sudo apt-get install libxml2-dev
sudo apt-get install apache2-dev
sudo apt-get install freetds-dev
sudo apt-get install libmysqlclient15-dev
